[package]
name = "lmc"
version = "0.1.0"
edition = "2021"
author = "h5law"
readme = "./README.md"
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
